### ISSUE TITLE
Modify tiro-notes directory

### ISSUE THREAD

**Issue by grebgreb** [dotgreg/tiro-notes#1]
Hi,
I've installed the app, but mistaked in the target directory where the notes are stored.
How can I change it?
Should I modify a config file? Delete the app (how?) and reinstall?
Thanks!

**Comment by dotgreg** [comment]
The config file is located here : ~/.tiro-config.json.
So you can either modify the path directly or delete the file and restart Tiro to be prompted again.
Settings functionality is under development to be able to do it without restarting tiro.
